const fs = require('fs');
const path = require('path');
const IdeaCapturer = require('./ideaCapturer/ideaCapturer');
const IdeaGenerator = require('./ideaGenerator');
const TaskQueue = require('./taskQueue/taskQueue');
const iFlowEngine = require('./iflowEngine/iflowEngine');
const CodeRepository = require('./codeRepository/codeRepository');
const Monitor = require('./monitor/monitor');
const WebServer = require('./server');
const logger = require('./utils/logger');

class ContinuousDevSystem {
  constructor(configPath) {
    this.config = this.loadConfig(configPath);
    this.isRunning = false;
    this.checkInterval = null;
    this.webServer = null;
    this.isProcessingTasks = false;

    this.initializeComponents();
  }

  loadConfig(configPath) {
    try {
      const configContent = fs.readFileSync(configPath, 'utf-8');
      return JSON.parse(configContent);
    } catch (error) {
      if (error && error.code === 'ENOENT') {
        logger.warn('未找到 config.json，已使用默认配置启动', { configPath });
        return this.getDefaultConfig();
      }

      logger.error('加载配置文件失败', { configPath, error: error.message });
      throw error;
    }
  }

  getDefaultConfig() {
    return {
      system: {
        name: 'iFlow Continuous Development System',
        version: '1.0.0',
        checkInterval: 60000,
        maxConcurrentTasks: 3
      },
      ideaSources: {
        fileWatcher: {
          enabled: true,
          watchDirectory: './ideas',
          filePattern: '*.txt'
        },
        simulatedCommunity: {
          enabled: true,
          updateInterval: 300000
        },
        randomPainPoints: {
          enabled: true,
          generateInterval: 600000
        }
      },
      taskQueue: {
        maxSize: 100,
        priorityLevels: ['high', 'medium', 'low']
      },
      codeRepository: {
        outputDirectory: './generated-code',
        autoCommit: false,
        commitMessage: 'Auto-generated by iFlow Continuous Dev'
      },
      logging: {
        level: 'info',
        directory: './logs',
        maxFiles: 10,
        maxSize: '10m'
      },
      iflow: {
        enabled: true,
        timeout: 300000,
        logLevel: 'INFO',
        autoStartProcess: true,
        permissionMode: 'manual',
        autoApproveTypes: [],
        fileAccess: true,
        fileReadOnly: false
      }
    };
  }

  initializeComponents() {
    this.ideaCapturer = new IdeaCapturer(this.config);
    this.ideaGenerator = new IdeaGenerator(this.config);
    this.taskQueue = new TaskQueue(this.config);
    this.iflowEngine = new iFlowEngine(this.config);
    this.codeRepository = new CodeRepository(this.config);
    this.monitor = new Monitor(this.config);
    this.webServer = new WebServer(this);

    this.setupEventListeners();
    this.setupLogStreaming();
  }

  setupLogStreaming() {
    // Stream structured logs to the web UI for real-time troubleshooting.
    try {
      if (logger && logger.events && typeof logger.events.on === 'function') {
        logger.events.on('log', (entry) => {
          if (!entry) return;
          this.broadcastToWeb('log', entry);
        });
      }
    } catch {
      // ignore
    }
  }

  setupEventListeners() {
    this.ideaCapturer.on('idea', (idea) => {
      this.handleNewIdea(idea);
    });

    this.iflowEngine.on('taskStream', (payload) => {
      this.broadcastToWeb('taskStream', payload);
    });

    this.taskQueue.on('taskAdded', (task) => {
      this.monitor.incrementMetric('totalTasks');
      logger.info('任务已添加', { taskId: task.id, priority: task.priority });
      this.broadcastToWeb('taskUpdate', task);
      this.processTasks();
    });

    this.taskQueue.on('taskStarted', (task) => {
      logger.info('任务开始处理', { taskId: task.id });
      this.broadcastToWeb('taskUpdate', task);
    });

    this.taskQueue.on('taskCompleted', (task) => {
      this.monitor.incrementMetric('completedTasks');
      const duration = this.calculateDuration(task.startedAt, task.completedAt);
      this.monitor.recordTaskDuration(duration);
      logger.info('任务完成', { taskId: task.id });

      // 广播新代码
      const outputFile = task.result?.outputFile || task.result?.output?.outputFile;
      if (outputFile) {
        const codeContent = this.readCodeFile(outputFile);
        this.broadcastToWeb('newCode', {
          taskId: task.id,
          content: codeContent,
          createdAt: task.completedAt
        });
      }

      this.broadcastToWeb('taskUpdate', task);
      this.broadcastStats();
      this.processTasks();
    });

    this.taskQueue.on('taskFailed', (task) => {
      this.monitor.incrementMetric('failedTasks');
      logger.error('任务失败', { taskId: task.id, error: task.error });
      this.broadcastToWeb('taskUpdate', task);
      this.broadcastStats();
      this.processTasks();
    });

    this.monitor.on('healthAlert', (alert) => {
      logger.warn('健康警报', { level: alert.level, failureRate: alert.failureRate });
    });
  }

  readCodeFile(filePath) {
    try {
      if (fs.existsSync(filePath)) {
        return fs.readFileSync(filePath, 'utf-8');
      }
    } catch (error) {
      logger.error('读取代码文件失败', { filePath, error: error.message });
    }
    return '';
  }

  handleNewIdea(idea) {
    this.monitor.incrementMetric('totalIdeas');

    // 确保 Web 界面添加的想法也被记录到 capturedIdeas
    if (idea.source === 'web' && !this.ideaCapturer.capturedIdeas.find(i => i.id === idea.id)) {
      this.ideaCapturer.capturedIdeas.push(idea);
    }

    logger.info('收到新想法', { ideaId: idea.id, content: idea.content });

    const added = this.taskQueue.addTask(idea);
    if (!added) {
      logger.warn('任务队列已满，想法被忽略', { ideaId: idea.id });
    } else {
      this.broadcastToWeb('newIdea', idea);
      this.broadcastStats();
    }
  }

  broadcastToWeb(event, data) {
    if (this.webServer) {
      this.webServer.broadcast(event, data);
    }
  }

  broadcastStats() {
    const stats = {
      ...this.monitor.getFormattedMetrics(),
      ...this.taskQueue.getStats(),
      ...this.ideaCapturer.getStats()
    };
    this.broadcastToWeb('stats', stats);
  }

  async start() {
    if (this.isRunning) {
      logger.warn('系统已在运行中');
      return;
    }

    logger.info('========================================');
    logger.info('iFlow Continuous Development System');
    logger.info('24小时不间断自动化开发系统');
    logger.info('========================================');

    this.isRunning = true;

    try {
      // 启动 Web 服务器
      await this.webServer.start(8080);

      // 启动其他组件
      this.ideaCapturer.start();
      this.monitor.start();

      this.checkInterval = setInterval(() => {
        this.processTasks();
      }, this.config.system.checkInterval);

      logger.info('系统启动成功');
      logger.info('开始持续捕获想法并执行开发任务...');

      this.displayStatus();
    } catch (error) {
      logger.error('系统启动失败', { error: error.message });
      this.stop();
      throw error;
    }
  }

  async processTasks() {
    // ✅ 改进：提前检查所有条件
    if (!this.isRunning || this.isProcessingTasks) {
      return;
    }

    this.isProcessingTasks = true;
    try {
      const maxConcurrent = this.config.system.maxConcurrentTasks;
      const currentTasks = this.iflowEngine.getActiveTaskCount();

      if (currentTasks >= maxConcurrent) {
        return;
      }

      const availableSlots = maxConcurrent - currentTasks;
      const tasksToProcess = Math.min(availableSlots, this.taskQueue.queue.length);

      // ✅ 不再提前返回，确保 finally 总是执行
      if (tasksToProcess > 0) {
        logger.info(`开始处理 ${tasksToProcess} 个任务`, { currentTasks, maxConcurrent });

        for (let i = 0; i < tasksToProcess; i++) {
          const task = this.taskQueue.getNextTask();
          if (!task) {
            break;
          }

          this.executeTask(task);
        }
      }
    } finally {
      // ✅ 保证总是释放锁
      this.isProcessingTasks = false;
    }
  }

  async executeTask(task) {
    const startTime = Date.now();

    try {
      const result = await this.iflowEngine.executeTask(task);

      if (result.success) {
        this.codeRepository.saveCode(task, result);
        this.taskQueue.completeTask(task.id, result);
      } else {
        this.taskQueue.failTask(task.id, result.error);
      }
    } catch (error) {
      logger.error('任务执行异常', { taskId: task.id, error: error.message });
      this.taskQueue.failTask(task.id, error.message);
    }
  }

  calculateDuration(startTime, endTime) {
    const start = new Date(startTime);
    const end = new Date(endTime);
    return Math.round((end - start) / 1000);
  }

  stop() {
    if (!this.isRunning) {
      return;
    }

    logger.info('正在停止系统...');

    this.isRunning = false;

    if (this.checkInterval) {
      clearInterval(this.checkInterval);
    }

    this.ideaCapturer.stop();
    this.monitor.stop();
    this.iflowEngine.terminateAllTasks();

    if (this.webServer) {
      this.webServer.stop();
    }

    logger.info('系统已停止');
    this.displayStatus();
  }

  displayStatus() {
    const metrics = this.monitor.getFormattedMetrics();
    const queueStats = this.taskQueue.getStats();
    const repoStats = this.codeRepository.getRepositoryStats();
    const ideaStats = this.ideaCapturer.getStats();

    console.log('\n========================================');
    console.log('系统状态');
    console.log('========================================');
    console.log(`运行状态: ${this.isRunning ? '运行中' : '已停止'}`);
    console.log(`健康状态: ${metrics.systemHealth}`);
    console.log(`运行时间: ${metrics.uptime}`);
    console.log('');
    console.log('想法统计:');
    console.log(`  总想法数: ${ideaStats.totalIdeas}`);
    console.log(`  按来源: ${JSON.stringify(ideaStats.bySource)}`);
    console.log(`  按优先级: ${JSON.stringify(ideaStats.byPriority)}`);
    console.log('');
    console.log('任务队列:');
    console.log(`  待处理: ${queueStats.pending}`);
    console.log(`  处理中: ${queueStats.processing}`);
    console.log(`  已完成: ${queueStats.completed}`);
    console.log(`  失败: ${queueStats.failed}`);
    console.log(`  总计: ${queueStats.total}`);
    console.log('');
    console.log('性能指标:');
    console.log(`  成功率: ${metrics.successRate}`);
    console.log(`  平均任务时长: ${metrics.formattedAverageTaskDuration}`);
    console.log('');
    if (repoStats) {
      console.log('代码仓库:');
      console.log(`  文件数: ${repoStats.totalFiles}`);
      console.log(`  提交数: ${repoStats.totalCommits}`);
      console.log(`  大小: ${this.formatBytes(repoStats.directorySize)}`);
    }
    console.log('========================================\n');
  }

  formatBytes(bytes) {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  }

  generateReport() {
    const report = this.monitor.generateReport();
    const reportPath = path.join(__dirname, '../logs', 'report.md');

    try {
      fs.writeFileSync(reportPath, report, 'utf-8');
      logger.info('报告已生成', { reportPath });
      return reportPath;
    } catch (error) {
      logger.error('生成报告失败', { error: error.message });
      return null;
    }
  }
}

const configPath = path.join(__dirname, '../config.json');
const system = new ContinuousDevSystem(configPath);

if (require.main === module) {
  system.start().catch(error => {
    logger.error('系统启动失败', { error: error.message });
    process.exit(1);
  });

  process.on('SIGINT', () => {
    logger.info('收到停止信号');
    system.stop();
    system.generateReport();
    process.exit(0);
  });

  process.on('SIGTERM', () => {
    logger.info('收到终止信号');
    system.stop();
    system.generateReport();
    process.exit(0);
  });

  setInterval(() => {
    system.displayStatus();
  }, 300000);
}

module.exports = ContinuousDevSystem;
