const fs = require('fs');
const path = require('path');
const IdeaCapturer = require('./ideaCapturer/ideaCapturer');
const { IdeaGenerator } = require('./ideaGenerator');
const TaskQueue = require('./taskQueue/taskQueue');
const iFlowEngine = require('./iflowEngine/iflowEngine');
const CodeRepository = require('./codeRepository/codeRepository');
const Monitor = require('./monitor/monitor');
const WebServer = require('./server');
const logger = require('./utils/logger');

class ContinuousDevSystem {
  constructor(configPath) {
    this.config = this.loadConfig(configPath);
    this.isRunning = false;
    this.checkInterval = null;
    this.webServer = null;
    this.isProcessingTasks = false;

    this.initializeComponents();
  }

  loadConfig(configPath) {
    try {
      const configContent = fs.readFileSync(configPath, 'utf-8');
      return JSON.parse(configContent);
    } catch (error) {
      if (error && error.code === 'ENOENT') {
        logger.warn('未找到 config.json，已使用默认配置启动', { configPath });
        return this.getDefaultConfig();
      }

      logger.error('加载配置文件失败', { configPath, error: error.message });
      throw error;
    }
  }

  getDefaultConfig() {
    return {
      system: {
        name: 'iFlow Continuous Development System',
        version: '1.0.0',
        checkInterval: 60000,
        maxConcurrentTasks: 3
      },
      ideaSources: {
        fileWatcher: {
          enabled: true,
          watchDirectory: './ideas',
          filePattern: '*.txt'
        },
        simulatedCommunity: {
          enabled: true,
          updateInterval: 300000
        },
        randomPainPoints: {
          enabled: true,
          generateInterval: 600000
        }
      },
      taskQueue: {
        maxSize: 100,
        priorityLevels: ['high', 'medium', 'low']
      },
      codeRepository: {
        outputDirectory: './generated-code',
        autoCommit: false,
        commitMessage: 'Auto-generated by iFlow Continuous Dev'
      },
      logging: {
        level: 'info',
        directory: './logs',
        maxFiles: 10,
        maxSize: '10m'
      },
      iflow: {
        enabled: true,
        timeout: 300000,
        logLevel: 'INFO',
        autoStartProcess: true,
        permissionMode: 'manual',
        autoApproveTypes: [],
        fileAccess: true,
        fileReadOnly: false
      }
    };
  }

  initializeComponents() {
    this.ideaCapturer = new IdeaCapturer(this.config);
    this.ideaGenerator = new IdeaGenerator(this.config);
    this.taskQueue = new TaskQueue(this.config);
    this.iflowEngine = new iFlowEngine(this.config);
    this.codeRepository = new CodeRepository(this.config);
    this.monitor = new Monitor(this.config);
    this.webServer = new WebServer(this);

    this.setupEventListeners();
    this.setupLogStreaming();
  }

  setupLogStreaming() {
    // Stream structured logs to the web UI for real-time troubleshooting.
    try {
      if (logger && logger.events && typeof logger.events.on === 'function') {
        logger.events.on('log', (entry) => {
          if (!entry) return;
          this.broadcastToWeb('log', entry);
        });
      }
    } catch {
      // ignore
    }
  }

  setupEventListeners() {
    this.ideaCapturer.on('idea', (idea) => {
      this.handleNewIdea(idea);
    });

    this.iflowEngine.on('taskStream', (payload) => {
      this.broadcastToWeb('taskStream', payload);
    });

    this.taskQueue.on('taskAdded', (task) => {
      this.monitor.incrementMetric('totalTasks');
      logger.info('任务已添加', { taskId: task.id, priority: task.priority });
      this.broadcastToWeb('taskUpdate', task);
      this.processTasks();
    });

    this.taskQueue.on('taskStarted', (task) => {
      logger.info('任务开始处理', { taskId: task.id });
      this.broadcastToWeb('taskUpdate', task);
    });

    this.taskQueue.on('taskCompleted', (task) => {
      this.monitor.incrementMetric('completedTasks');
      const duration = this.calculateDuration(task.startedAt, task.completedAt);
      this.monitor.recordTaskDuration(duration);
      logger.info('任务完成', { taskId: task.id });

      // 广播新代码
      const outputFile = task.result?.outputFile || task.result?.output?.outputFile;
      if (outputFile) {
        const codeContent = this.readCodeFile(outputFile);
        this.broadcastToWeb('newCode', {
          taskId: task.id,
          content: codeContent,
          createdAt: task.completedAt
        });
      }

      this.broadcastToWeb('taskUpdate', task);
      this.broadcastStats();
      this.processTasks();
    });

    this.taskQueue.on('taskFailed', (task) => {
      this.monitor.incrementMetric('failedTasks');
      logger.error('任务失败', { taskId: task.id, error: task.error });
      this.broadcastToWeb('taskUpdate', task);
      this.broadcastStats();
      this.processTasks();
    });

    this.monitor.on('healthAlert', (alert) => {
      logger.warn('健康警报', { level: alert.level, failureRate: alert.failureRate });
    });

    // 🐂 牛马工作站事件转发
    const autoIterator = this.iflowEngine.autoIterator;
    if (autoIterator) {
      autoIterator.on('niuMaStart', (p) => {
        logger.debug('🐂 牛马开始事件', { appId: p.appId });
        this.broadcastToWeb('niuMaStart', p);
      });

      autoIterator.on('niuMaStop', (p) => {
        logger.debug('🐂 牛马停止事件', { appId: p.appId });
        this.broadcastToWeb('niuMaStop', p);
      });

      // 迭代开始时，推送任务更新给前端
      autoIterator.on('iterationStart', (p) => {
        logger.debug('🐂 牛马迭代开始', { appId: p.appId, taskId: p.taskId });
        this.broadcastToWeb('iterationStart', p);

        // 构造一个模拟的任务对象，让前端显示气泡
        const fakeTask = {
          id: p.taskId,
          status: 'processing',
          ideaKey: p.ideaKey,
          createdAt: new Date().toISOString(),
          idea: { content: `🐂 NiuMa 自动迭代 #${p.iteration}` },
          revision: p.iteration,
          isNiuMa: true
        };
        this.broadcastToWeb('taskUpdate', fakeTask);
      });

      autoIterator.on('iterationComplete', (p) => {
        logger.debug('🐂 牛马迭代完成', { appId: p.appId, iteration: p.iteration });
        this.broadcastToWeb('iterationComplete', p);
      });

      autoIterator.on('iterationError', (p) => {
        logger.warn('🐂 牛马迭代失败', { appId: p.appId, error: p.error });
        this.broadcastToWeb('iterationError', p);
      });

      autoIterator.on('niuMaCircuitBreak', (p) => {
        logger.error('🐂 牛马熔断', { appId: p.appId, consecutiveErrors: p.consecutiveErrors });
        this.broadcastToWeb('niuMaCircuitBreak', p);
      });
    }
  }

  readCodeFile(filePath) {
    try {
      if (fs.existsSync(filePath)) {
        return fs.readFileSync(filePath, 'utf-8');
      }
    } catch (error) {
      logger.error('读取代码文件失败', { filePath, error: error.message });
    }
    return '';
  }

  handleNewIdea(idea) {
    this.monitor.incrementMetric('totalIdeas');

    // 确保 Web 界面添加的想法也被记录到 capturedIdeas
    if (idea.source === 'web' && !this.ideaCapturer.capturedIdeas.find(i => i.id === idea.id)) {
      this.ideaCapturer.capturedIdeas.push(idea);
    }

    logger.info('收到新想法', { ideaId: idea.id, content: idea.content });

    const added = this.taskQueue.addTask(idea);
    if (!added) {
      logger.warn('任务队列已满，想法被忽略', { ideaId: idea.id });
    } else {
      this.broadcastToWeb('newIdea', idea);
      this.broadcastStats();
    }
  }

  broadcastToWeb(event, data) {
    if (this.webServer) {
      this.webServer.broadcast(event, data);
    }
  }

  broadcastStats() {
    const stats = {
      ...this.monitor.getFormattedMetrics(),
      ...this.taskQueue.getStats(),
      ...this.ideaCapturer.getStats()
    };
    this.broadcastToWeb('stats', stats);
  }

  async start() {
    if (this.isRunning) {
      logger.warn('系统已在运行中');
      return;
    }

    logger.info('========================================');
    logger.info('iFlow Continuous Development System');
    logger.info('24小时不间断自动化开发系统');
    logger.info('========================================');

    this.isRunning = true;

    try {
      // 启动 Web 服务器
      await this.webServer.start(8080);

      // 启动其他组件
      this.ideaCapturer.start();
      this.monitor.start();

      this.checkInterval = setInterval(() => {
        this.processTasks();
      }, this.config.system.checkInterval);

      logger.info('系统启动成功');
      logger.info('开始持续捕获想法并执行开发任务...');

      this.displayStatus();
    } catch (error) {
      logger.error('系统启动失败', { error: error.message });
      this.stop();
      throw error;
    }
  }

  async processTasks() {
    // ✅ 改进：提前检查所有条件
    if (!this.isRunning || this.isProcessingTasks) {
      return;
    }

    this.isProcessingTasks = true;
    try {
      const maxConcurrent = this.config.system.maxConcurrentTasks;
      const currentTasks = this.iflowEngine.getActiveTaskCount();

      if (currentTasks >= maxConcurrent) {
        return;
      }

      const availableSlots = maxConcurrent - currentTasks;
      const tasksToProcess = Math.min(availableSlots, this.taskQueue.queue.length);

      // ✅ 不再提前返回，确保 finally 总是执行
      if (tasksToProcess > 0) {
        logger.info(`开始处理 ${tasksToProcess} 个任务`, { currentTasks, maxConcurrent });

        for (let i = 0; i < tasksToProcess; i++) {
          const task = this.taskQueue.getNextTask();
          if (!task) {
            break;
          }

          this.executeTask(task);
        }
      }
    } finally {
      // ✅ 保证总是释放锁
      this.isProcessingTasks = false;
    }
  }

  async executeTask(task) {
    const startTime = Date.now();

    try {
      const result = await this.iflowEngine.executeTask(task);

      if (result.success) {
        this.codeRepository.saveCode(task, result);
        this.taskQueue.completeTask(task.id, result);
      } else {
        this.taskQueue.failTask(task.id, result.error);
      }
    } catch (error) {
      logger.error('任务执行异常', { taskId: task.id, error: error.message });
      this.taskQueue.failTask(task.id, error.message);
    }
  }

  calculateDuration(startTime, endTime) {
    const start = new Date(startTime);
    const end = new Date(endTime);
    return Math.round((end - start) / 1000);
  }

  stop() {
    if (!this.isRunning) {
      return;
    }

    logger.info('🛑 正在停止系统（包括所有子进程）...');

    this.isRunning = false;

    if (this.checkInterval) {
      clearInterval(this.checkInterval);
    }

    // 停止想法生成器
    if (this.ideaGenerator && this.ideaGenerator.enabled) {
      this.ideaGenerator.stop();
    }

    this.ideaCapturer.stop();
    this.monitor.stop();

    // 1. 停止所有自动迭代器（牛马）
    if (this.iflowEngine && this.iflowEngine.autoIterator) {
      logger.info('🐂 正在停止所有牛马...');
      this.iflowEngine.autoIterator.stopAll();
    }

    // 2. 终止所有正在执行的任务
    this.iflowEngine.terminateAllTasks();

    // 3. 停止所有已启动的生成应用
    if (this.iflowEngine) {
      logger.info('🔌 正在停止所有生成的应用...');
      this.iflowEngine.stopAllApps();
    }

    // 4. 释放所有会话（杀死 iFlow CLI 进程）
    if (this.iflowEngine && this.iflowEngine.sessionManager) {
      logger.info('🧹 正在清理所有 iFlow 会话...');
      this.iflowEngine.sessionManager.terminateAllSessions();
    }

    if (this.webServer) {
      this.webServer.stop();
    }

    logger.info('✅ 系统已完全停止，所有子进程已清理');
    this.displayStatus();
  }

  displayStatus() {
    const metrics = this.monitor.getFormattedMetrics();
    const queueStats = this.taskQueue.getStats();
    const repoStats = this.codeRepository.getRepositoryStats();
    const ideaStats = this.ideaCapturer.getStats();

    console.log('\n========================================');
    console.log('系统状态');
    console.log('========================================');
    console.log(`运行状态: ${this.isRunning ? '运行中' : '已停止'}`);
    console.log(`健康状态: ${metrics.systemHealth}`);
    console.log(`运行时间: ${metrics.uptime}`);
    console.log('');
    console.log('想法统计:');
    console.log(`  总想法数: ${ideaStats.totalIdeas}`);
    console.log(`  按来源: ${JSON.stringify(ideaStats.bySource)}`);
    console.log(`  按优先级: ${JSON.stringify(ideaStats.byPriority)}`);
    console.log('');
    console.log('任务队列:');
    console.log(`  待处理: ${queueStats.pending}`);
    console.log(`  处理中: ${queueStats.processing}`);
    console.log(`  已完成: ${queueStats.completed}`);
    console.log(`  失败: ${queueStats.failed}`);
    console.log(`  总计: ${queueStats.total}`);
    console.log('');
    console.log('性能指标:');
    console.log(`  成功率: ${metrics.successRate}`);
    console.log(`  平均任务时长: ${metrics.formattedAverageTaskDuration}`);
    console.log('');
    if (repoStats) {
      console.log('代码仓库:');
      console.log(`  文件数: ${repoStats.totalFiles}`);
      console.log(`  提交数: ${repoStats.totalCommits}`);
      console.log(`  大小: ${this.formatBytes(repoStats.directorySize)}`);
    }
    console.log('========================================\n');
  }

  formatBytes(bytes) {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round(bytes / Math.pow(k, i) * 100) / 100 + ' ' + sizes[i];
  }

  generateReport() {
    const report = this.monitor.generateReport();
    const reportPath = path.join(__dirname, '../logs', 'report.md');

    try {
      fs.writeFileSync(reportPath, report, 'utf-8');
      logger.info('报告已生成', { reportPath });
      return reportPath;
    } catch (error) {
      logger.error('生成报告失败', { error: error.message });
      return null;
    }
  }
}

const configPath = path.join(__dirname, '../config.json');
const system = new ContinuousDevSystem(configPath);

if (require.main === module) {
  system.start().catch(error => {
    logger.error('系统启动失败', { error: error.message });
    process.exit(1);
  });

  // 正常退出信号
  process.on('SIGINT', () => {
    logger.info('收到停止信号 (SIGINT)');
    system.stop();
    system.generateReport();
    process.exit(0);
  });

  process.on('SIGTERM', () => {
    logger.info('收到终止信号 (SIGTERM)');
    system.stop();
    system.generateReport();
    process.exit(0);
  });

  // 🚨 异常退出处理 - 确保子进程被清理
  process.on('uncaughtException', (error) => {
    logger.error('🚨 未捕获的异常！正在紧急清理子进程...', { error: error.message, stack: error.stack });
    try {
      system.stop();
    } catch (e) {
      logger.error('紧急清理失败', { error: e.message });
    }
    process.exit(1);
  });

  process.on('unhandledRejection', (reason, promise) => {
    logger.error('🚨 未处理的 Promise 拒绝！', { reason: String(reason) });
    // 不退出，但记录警告
  });

  process.on('beforeExit', (code) => {
    logger.info('进程即将退出，执行最终清理', { exitCode: code });
    try {
      system.stop();
    } catch (e) { }
  });

  // Windows 特定：处理控制台关闭事件
  if (process.platform === 'win32') {
    const readline = require('readline');
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    rl.on('SIGINT', () => process.emit('SIGINT'));
  }

  setInterval(() => {
    system.displayStatus();
  }, 300000);
}

module.exports = ContinuousDevSystem;
